apiVersion: v2
name: keycloak
description: A Helm chart for Keycloak - Open Source Identity and Access Management
type: application
version: 1.1.1
appVersion: "26.4.0"
keywords:
  - keycloak
  - identity
  - access
  - authentication
  - authorization
home: https://www.keycloak.org/
sources:
  - https://github.com/quixio/keycloak.helm
maintainers:
  - name: Quique
    email: quique@quix.io

