{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-postgresql
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.keycloak.database.username | b64enc | quote }}
  password: {{ .Values.keycloak.database.password | b64enc | quote }}
{{- end }}


